core/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('success/', views.index, name='success'),
]

mg_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('success/', include('core.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
#  this tell django where to find the media files

core/models.py
from ctypes.wintypes import SIZE
from django.db import models


# HOME SECTION

class Home(models.Model):
    name = models.CharField(max_length=50)
    greetings_1 = models.CharField(max_length=100, blank=True)
    #greetings_2 = models.CharField(max_length=100, blank=True)
    picture = models.ImageField(upload_to='picture/', null=True)
    # save time when modified
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


# ABOUT SECTION

class About(models.Model):
    heading = models.CharField(max_length=50)
    career = models.CharField(max_length=50)
    description = models.TextField(blank=False)
    profile_img = models.ImageField(upload_to='profile/')

    updated = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.career


class Profile(models.Model):
    about = models.ForeignKey(About, on_delete=models.CASCADE)
    social_name = models.CharField(max_length=10)
    link = models.URLField(max_length=200)


# SKILLS SECTION

class Category(models.Model):
    name = models.CharField(max_length=50)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Skill'
        verbose_name_plural = 'Skills'

    def __str__(self):
        return self.name


class Skills(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    skill_name = models.CharField(max_length=50)


# PORTFOLIO SECTION

class Portfolio(models.Model):
    image = models.ImageField(upload_to='portfolio/')
    link = models.URLField(max_length=200)

    def __str__(self):
        return f'Portfolio {self.id}'

core/forms.py
from django import forms


def should_be_empty(value):
    if value:
        raise forms.ValidationError('Field is not empty')


class ContactForm(forms.Form):
    subject = forms.CharField(max_length=50)
    message = forms.CharField(widget=forms.Textarea)
    sender = forms.EmailField()
    forcefield = forms.CharField(
        required=False, widget=forms.HiddenInput, label="Leave empty", validators=[should_be_empty])
    cc_myself = forms.BooleanField(required=False)

core/views.py
from django.shortcuts import render, redirect
from .models import Home, About, Profile, Category, Skills, Portfolio
from .forms import ContactForm
from django.core.mail import send_mail
from django.contrib import messages


def index(request):

    # Home
    home = Home.objects.latest('updated')

    # About
    about = About.objects.latest('updated')
    profiles = Profile.objects.filter(about=about)

    # Skills
    categories = Category.objects.all()

    # Portfolios
    portfolios = Portfolio.objects.all()

    context = {
        'home': home,
        'about': about,
        'profiles': profiles,
        'categories': categories,
        'portfolios': portfolios,
    }

    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = ContactForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            sender = form.cleaned_data['sender']
            cc_myself = form.cleaned_data['cc_myself']

            recipients = ['mg.sharp@mail.com']
            if cc_myself:
                recipients.append(sender)
            send_mail(subject, message, sender, recipients, fail_silently=False,
                      auth_user=None, auth_password=None, connection=None, html_message=None)
            messages.add_message(request, messages.INFO,
                                 'Thank You! Your message was successfully sent!')
            return redirect('/#contact')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = ContactForm()

    return render(request, 'index.html', context)

core/templates/index.html
{% load static %}
<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- ===== CSS ===== -->
        <link rel="stylesheet" href="{% static 'assets/css/styles.css' %}">

        <!-- ===== BOX ICONS ===== -->
        <link href='https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css' rel='stylesheet'>
        

        <!-- Extra CSS -->
        <style>
            .home__img{
                image-rendering: auto;
                image-rendering: crisp-edges;
                image-rendering: pixelated;
              
                /* Safari seems to support, but seems deprecated and does the same thing as the others. */
                image-rendering: -webkit-optimize-contrast;
                height: 850px;
                width: 400px;
                left: 52%;
            }
            .about__img img{
                width: 200px;
                
            }
        </style>

        <title>Portfolio responsive complete</title>
    </head>
    <body>

        
        <!--===== HEADER =====-->
        <header class="l-header">
            <nav class="nav bd-grid">
                
                <div>
                    <a href="#" class="nav__logo">{{ home.name }}</a>
                </div>

                <div class="nav__menu" id="nav-menu">
                    <ul class="nav__list">
                        <li class="nav__item"><a href="#home" class="nav__link active">Home</a></li>
                        <li class="nav__item"><a href="#about" class="nav__link">About</a></li>
                        <li class="nav__item"><a href="#skills" class="nav__link">Skills</a></li>
                        <li class="nav__item"><a href="#portfolio" class="nav__link">Portfolios</a></li>
                        <li class="nav__item"><a href="#contact" class="nav__link">Contact</a></li>
                    </ul>
                </div>

                <div class="nav__toggle" id="nav-toggle">
                    <i class='bx bx-menu'></i>
                </div>
            </nav>
        </header>

        <main class="l-main">
            <!--===== HOME =====-->
            <section class="home" id="home">
                <div class="home__container bd-grid">
                    <h1 class="home__title"><span>{{ home.greetings_1 }}</span></h1>

                    <div class="home__scroll">
                        <a href="#about" class="home__scroll-link"><i class='bx bx-up-arrow-alt' ></i>Scroll down</a>
                    </div>

                    <img src="{{ home.picture.url }}" alt="" class="home__img">
                </div>
            </section>
            
            <!--===== ABOUT =====-->
            <section class="about section" id="about">
                <h2 class="section-title">About</h2>

                <div class="about__container bd-grid">
                    <div class="about__img">
                        <img src="{{ about.profile_img.url }}" alt="">
                    </div>

                    <div>
                        <h2 class="about__subtitle">{{ about.heading }}</h2>
                        <span class="about__profession">{{ about.career }}</span>
                        <p class="about__text">{{ about.description|safe }}</p>
                        <a class="about__cv" href="\static\assets\files\Curriculum Vitae - Mantas Gustas.docx" download>Download My CV</a>
                    </div>
                        
                        <div class="about__social">

                            {% for profile in about.profile_set.all %}
                                <a href="{{ profile.link }}" class="about__social-icon">
                                    <i class='bx bxl-{{ profile.social_name }}' ></i>
                                </a>
                            {% endfor %}
                            
                        </div>
                    </div>
                </div>
            </section>

            <!--===== SKILLS =====-->
            <section class="skills section" id="skills">
                <h2 class="section-title">Skills</h2>

                <div class="skills__container bd-grid">
                    <div class="skills__box">
                        {% for category in categories %}
                        <h3 class="skills__subtitle">{{category.name}}</h3>
                            {% for skills in category.skills_set.all %}
                            
                                <span class="skills__name">{{skills.skill_name}}</span>
                            {% endfor %}
                        {% endfor %}
                        
                    </div>

                    <div class="skills__img">
                        <img src="{% static 'assets/img/skill.jpg' %}" alt="">
                    </div>
                </div>
            </section>

            <!--===== PORTFOLIO =====-->
            <section class="portfolio section" id="portfolio">
                <h2 class="section-title">Portfolios</h2>

                
                <div class="portfolio__container bd-grid">

                    {% for portfolio in portfolios %}
                    
                    <div class="portfolio__img">
                        <img src="{{ portfolio.image.url }}" alt="">

                        <div class="portfolio__link">
                            <a href="{{ portfolio.link }}" class="portfolio__link-name " target="_blank" >View details</a>
                        </div>
                    </div>

                    {% endfor %}
                    
                </div>
                
            </section>

            
            <!--===== CONTACT =====-->
            <section class="contact section" id="contact">
                <h2 class="section-title">Contact Me</h2>
                <div class="contact__container bd-grid">


                    <div class="contact__info">
                        <h3 class="contact__subtitle">EMAIL</h3>
                        <span class="contact__text">mg.sharp@mail.com</span>
                    </div>
                    
                    <div class="contact__info">
                        <h3 class="contact__subtitle">PHONE</h3>
                        <span class="contact__text">07376049111</span>
                    </div>
                   
                    
                    {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
                            {{ message }}
                        </li>
                        {% endfor %}
                    </ul>
                    {% else %}
                    
                    <form class="submit__form" action="" method="post">
                        {% csrf_token %}
                        <div>
                            <tr><label class="contact__subtitle" for="id_subject">Name:</label>
                                <input id="id_subject" type="text" name="subject" maxlength="100" required placeholder="Your Name"></tr>
                            <tr><label class="contact__subtitle" for="id_sender">Sender:</label>
                                <input type="email" name="sender" id="id_sender" required placeholder="Your Email Address"></tr>
                                <br/>
                            <p><label class="contact__subtitle" for="id_message">Message:</label></p>
                                <textarea name="message" id="id_message" required cols="0" rows="5" class="email__input"></textarea>
                            <p><input type="submit" value="Submit" name="ContactForm">
                                <label class="contact__subtitle" for="id_cc_myself">Cc myself:</label>
                                <input type="checkbox" name="cc_myself" id="id_cc_myself"></p>
                        </div>
                    </form>
                    {% endif %}
            </section>

        </main>

        <!--===== FOOTER =====-->
        <footer class="footer section">
            <div class="footer__container bd-grid">
                <div class="footer__data">
                    <h2 class="footer__title">Mantas Gustas</h2>
                    <p class="footer__text">I'm Mantas Gustas and this is my personal website which was created whilst watching a YouTube Portfolio tutorial</p>
                </div>

                <div class="footer__data">
                    <h2 class="footer__title">EXPLORE</h2>
                    <ul>
                        <li><a href="#home" class="footer__link">Home</a></li>
                        <li><a href="#about" class="footer__link">About</a></li>
                        <li><a href="#skills" class="footer__link">Skills</a></li>
                        <li><a href="#portfolio" class="footer__link">PortfoliosS</a></li>
                        <li><a href="#Contact" class="footer__link">Contact</a></li>
                    </ul>
                </div>
                
                <div class="footer__data">
                    <h2 class="footer__title">FOLLOW</h2>
                    <a href="https://uk.linkedin.com/in/mantas-gustas-442b43168?trk=people-guest_people_search-card&original_referer=https%3A%2F%2Fuk.linkedin.com%2Fpub%2Fdir%3FfirstName%3DMantas%26lastName%3DGustas%26trk%3Dhomep" 
                        class="footer__social" target="_blank"><i class='bx bxl-linkedin'></i></a>
                    <a href="https://github.com/Mantas-Gustas" class="footer__social" target="_blank"><i class='bx bxl-github' target="_blank"></i></a>
                    <!-- <a href="#" class="footer__social"><i class='bx bxl-sololearn' ></i></a> -->
                </div>


            </div>
        </footer>

        <!--===== SCROLL REVEAL =====-->
        <script src="https://unpkg.com/scrollreveal"></script>

        <!--===== MAIN JS =====-->
        <script src="{% static 'assets/js/main.js' %}"></script>
    </body>
</html>